### PR TITLE
Added footer menu

### PR DESCRIPTION
**Pull request by asmaaaah**
Screen Shot 2020-05-03 at 10 54 29 PM
Screen Shot 2020-05-03 at 10 55 31 PM

### CODE REVIEW

**Comment by asmaaaah** [comment]
New arrangement of badge page to adjust with the footer:
Screen Shot 2020-05-03 at 11 02 49 PM

**Comment by aniprasad** [comment]
I have a quick question, what do the icons mean?

**Comment by asmaaaah** [comment]
@aniprasad it's home, lessons and award. We can modify it later. And can add a description at hover.

**Comment by rampras3** [comment]
@natashadecoste @asmaaaah  perhaps Natasha can design icons for the footer and replace the current ones. For example, instead of the trophy it should be a badge since trophy is what they had in old ORT. (this can be low priority)

**Comment by asmaaaah** [comment]
@rampras3 the world page is not done yet, I can put the footer when it's complete. Right now I am not sure how @husseinfahmy is laying things out. Once hussein has implemented the module we can get rid of the start button and I can add the footer.


And yes we could definitely change the icons. But I just wanted to have something there instead of the round buttons. As you mentions it is low priority atm. We can open an issue for now

**Comment by rampras3** [comment]
> @rampras3 the world page is not done yet, I can put the footer when it's complete. Right now I am not sure how @husseinfahmy is laying things out. Once hussein has implemented the module we can get rid of the start button and I can add the footer.
> 
> And yes we could definitely change the icons. But I just wanted to have something there instead of the round buttons. As you mentions it is low priority atm. We can open an issue for now

Okay, the start button will probably be moved to the bottom sheet modal so you wont need to delete it, just open issue for this then.

**Comment by rampras3** [comment]
@husseinfahmy Can you add an instruction text that says "swipe to see the other worlds!" So they know to swipe

**Pull request merged**
